---

- name: Install Sysmon
  ansible.builtin.include_tasks: windows-install-sysmon.yml
  when: '"Windows" in ansible_distribution and win_install_sysmon == "1"'

- name: Deploy Config
  ansible.builtin.include_tasks: windows-config-sysmon.yml
  when: '"Windows" in ansible_distribution and win_sysmon_template!=""'
