---

- name: Install sysmon
  block:
    - name: Check if sysmon archive is present
      ansible.windows.win_stat:
        path: c:\Program Files\ansible\sysmon
      register: sysmondl

    - name: Create sysmon directory
      ansible.windows.win_file:
        path: c:\Program Files\ansible\sysmon
        state: directory
      when: not sysmondl.stat.exists

    - name: Install Sysmon with Choco
      chocolatey.chocolatey.win_chocolatey:
        name: Sysmon
        version: 15.0
        state: present

    # - name: Download sysmon
    #   ansible.windows.win_get_url:
    #     url: "{{ win_sysmon_url }}"
    #     dest: 'c:\Program Files\ansible\{{ win_sysmon_url | basename }}'
    #     timeout: 60
    #   when: not sysmondl.stat.exists

    # - name: Unzip sysmon
    #   community.windows.win_unzip:
    #     src: 'c:\Program Files\ansible\{{ win_sysmon_url | basename }}'
    #     dest: 'c:\Program Files\ansible\sysmon'
    #     creates: 'c:\Program Files\ansible\sysmon\sysmon.exe'
    #   when: not sysmondl.stat.exists

    # - name: Add sysmon to PATH
    #   ansible.windows.win_path:
    #     elements: 'c:\Program Files\ansible\sysmon'
    #   when: not sysmondl.stat.exists

- name: Deploy Symon
  when: win_sysmon_template != '' and not sysmondl.stat.exists
  block:
    - name: Copy Sysmon template
      ansible.windows.win_template:
        src: "{{ win_sysmon_template }}.j2"
        dest: 'c:\Program Files\ansible\{{ win_sysmon_template }}'
    - name: Install sysmon with defined config
      ansible.windows.win_command: '"c:\Program Files\ansible\sysmon\sysmon64.exe" -accepteula -i "c:\Program Files\ansible\{{ win_sysmon_template }}"'
