---

- name: Install tcpreplay
  become: true
  ansible.builtin.apt:
    name: tcpreplay
    state: present

- name: Add decrypted interface
  become: true
  ansible.builtin.copy:
    src: 50-decrypted
    dest: /etc/network/interfaces.d/50-decrypted
    owner: root
    group: root
    mode: 0644

- name: Copy tcpreplay service
  become: true
  ansible.builtin.copy:
    src: tcpreplay.service
    dest: /etc/systemd/system/tcpreplay.service
    owner: root
    group: root
    mode: 0644

- name: Start tcpreplay service
  become: true
  ansible.builtin.systemd:
    name: tcpreplay
    enabled: yes
    daemon_reload: yes