---

- name: install tcpreplay
  become: yes
  apt:
    name: tcpreplay
    state: present

- name: add decrypted interface
  become: yes
  copy:
    src: 50-decrypted
    dest: /etc/network/interfaces.d/50-decrypted

- name: copy tcpreplay service
  become: yes
  copy:
    src: tcpreplay.service
    dest: /etc/systemd/system/tcpreplay.service

- name: start tcpreplay service
  become: yes
  systemd:
    name: tcpreplay
    state: started
    enabled: yes
    daemon_reload: yes