---

- name: Create folder directory for inputs configuration
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: splunk
    group: splunk
    recurse: yes
  with_items:
    - /opt/splunk/etc/apps/inputs_app/local/

- name: Copy inputs.conf
  become: true
  ansible.builtin.template:
    src: inputs.conf.j2
    dest: /opt/splunk/etc/apps/inputs_app/local/inputs.conf
    owner: splunk
    group: splunk
  notify: restart splunk
