---

- name: Install Requirements
  become: yes
  apt:
    state: present 
    name:
      - jq 
      - whois
      - build-essential
      - git
      - unzip
      - mysql-server
      - redis-server
      - python3-pip

- name: Download yq
  become: yes
  get_url:
    url: https://github.com/mikefarah/yq/releases/download/v4.25.1/yq_linux_amd64
    dest: /usr/bin/yq
    mode: 0755