---

- name: Add sniff interface
  become: true
  ansible.builtin.copy:
    src: 49-sniff
    dest: /etc/network/interfaces.d/49-sniff
    owner: root
    group: root
    mode: 0644

- name: Copy node config
  become: true
  ansible.builtin.copy:
    src: node.cfg
    dest: /opt/zeek/etc/node.cfg
    owner: root
    group: root
    mode: 0644

- name: Copy zeek service
  become: true
  ansible.builtin.copy:
    src: zeek.service
    dest: /etc/systemd/system/zeek.service
    owner: root
    group: root
    mode: 0644

- name: Set logs to json
  become: true
  ansible.builtin.blockinfile:
    path: /opt/zeek/share/zeek/site/local.zeek
    insertafter: EOF
    create: true
    block: |
      @load tuning/json-logs
  notify: Deploy zeek config

- name: Set http2
  become: true
  ansible.builtin.blockinfile:
    path: /opt/zeek/share/zeek/site/local.zeek
    insertafter: EOF
    create: true
    block: |
      @load http2
  notify: Deploy zeek config

- name: Add JA3 to zeek config
  become: true
  ansible.builtin.blockinfile:
    path: /opt/zeek/share/zeek/site/local.zeek
    insertafter: EOF
    create: true
    block: | 
      @load ja3
  notify: Deploy zeek config

- name: Start Zeek service
  become: true
  ansible.builtin.systemd:
    name: zeek
    enabled: true
    daemon_reload: true

- name: Setup Filebeat
  become: true
  ansible.builtin.shell: filebeat modules enable zeek
  notify: Restart Filebeat
  when: zeek_filebeat=='1'

- name: Zeek Filebeat Configure
  ansible.builtin.copy:
    src: filebeat/zeek.yml
    dest: /etc/filebeat/modules.d/zeek.yml
    owner: root
    group: root
    mode: 0644
  notify: Restart Filebeat
  when: zeek_filebeat=='1'
