---

- name: Add sniff interface
  become: true
  ansible.builtin.copy:
    src: 49-sniff
    dest: /etc/network/interfaces.d/49-sniff
    owner: root
    group: root
    mode: 0644

- name: Copy node config
  become: true
  ansible.builtin.copy:
    src: node.cfg
    dest: /opt/zeek/etc/node.cfg
    owner: root
    group: root
    mode: 0644

- name: Copy zeek service
  become: true
  ansible.builtin.copy:
    src: zeek.service
    dest: /etc/systemd/system/zeek.service
    owner: root
    group: root
    mode: 0644

- name: Set logs to json
  become: true
  ansible.builtin.blockinfile:
    path: /opt/zeek/share/zeek/site/local.zeek
    insertafter: EOF
    create: true
    block: "@load tuning/json-logs"

- name: Start Zeek service
  become: true
  ansible.builtin.systemd:
    name: zeek
    enabled: true
    daemon_reload: true
