---

- name: Install requirements
  become: true
  ansible.builtin.apt:
    name:
      - cmake
      - gnupg2
      - libnghttp2-dev
      - libbrotli-dev
    state: present

- name: Deploy Zeek repo
  become: true
  ansible.builtin.copy:
    src: zeek.list
    dest: /etc/apt/sources.list.d/zeek.list

- name: Add Zeek Key
  become: true
  ansible.builtin.apt_key:
    url: https://download.opensuse.org/repositories/security:zeek/Debian_11/Release.key
    state: present

- name: Install Zeek
  become: true
  ansible.builtin.apt:
    name: zeek
    update_cache: true
    state: present
  register: zeek_update

- name: Install HTTP/2.0 Parser
  become: true
  ansible.builtin.shell: /opt/zeek/bin/zkg install --force zeek/mitrecnd/bro-http2
  when: zeek_update.changed
