---

- name: Install requirements
  become: true
  ansible.builtin.apt:
    name:
      - cmake
      - gnupg2
      - libnghttp2-dev
      - libbrotli-dev
    state: present

- name: Add Zeek Key
  become: true
  ansible.builtin.get_url:
    url: "https://download.opensuse.org/repositories/security:zeek/Debian_11/Release.key"
    dest: /etc/apt/trusted.gpg.d/zeek.asc
    mode: '0644'
    force: true

- name: Deploy Zeek repo
  become: true
  apt_repository:
    repo:  "deb [signed-by=/etc/apt/trusted.gpg.d/zeek.asc] http://download.opensuse.org/repositories/security:/zeek/Debian_11/ /"
    state: present
    update_cache: yes

- name: Install Zeek
  become: true
  ansible.builtin.apt:
    name: zeek
    update_cache: true
    state: present
  register: zeek_update

- name: Install HTTP/2.0 Parser
  become: true
  ansible.builtin.shell: /opt/zeek/bin/zkg install --force zeek/mitrecnd/bro-http2
  when: zeek_update.changed
