---

- name: "Change the hostname"
  ansible.windows.win_hostname:
    name: "{{ hostname }}"
  register: win_hostname

- name: Reboot if needed
  ansible.windows.win_reboot:
    reboot_timeout: 600
    post_reboot_delay: 30
  when: win_hostname.reboot_required