---
- name: "Read data files"
  hosts: all:!elk
  connection: local
  vars_files:
    - "{{data_path}}/config.json"
  tasks:
    - name: Save the Json data to a Variable as a Fact
      ansible.builtin.set_fact:
        lab: "{{ lab }}"
        cacheable: true
