- name: Setup INETSIM host
  hosts: inetsim_role
  gather_facts: true
  vars:
    hostname: inetsim
    elastic_non_oss: 1
    zeek_filebeat: 1
    polar_proxy: 1
    inetsim: 1
    set_hostname: 0
    setup_gateway: 1
    elastic_oss: 0
  roles:
    - linux_common
    - inetsim
    - polarproxy
    - tcpreplay
    - {role: 'gateway', tags: ['gateway']}
    - elastic_repo
    - filebeat
    - zeek
    - reboot
