- hosts: all
  gather_facts: true
  vars:
    hostname: inetsim
    elastic_non_oss: 1
    zeek_filebeat: 1
    polar_proxy: 1
    inetsim: 1
    set_hostname: 0
    setup_gateway: 1
  roles:
    - linux_common
    - inetsim
    - polarproxy
    - tcpreplay
    - zeek
    - gateway
    - elastic_repo
    - filebeat
    - reboot
