- name: Setup Elastic SIEM Env
  hosts: logger_role:&elastic_siem_role
  gather_facts: true
  vars:
    hostname: logger
    set_hostname: '0'
    opensearch_output: '1'
    logstash_logscale: '1'
  roles:
    - {role: 'linux_common' }
    - {role: 'docker' }
    - {role: 'elastic_repo' }
    - {role: 'elastic' }
    - {role: 'logging/logstash' }
