---

- name: Install Logstash
  ansible.builtin.include_tasks: install-linux-logstash.yml
  when: ('logstash_role' in group_names or 'logstash_oss_role' in group_names) and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
- name: Configure Logstash User and ILM for Elasticsearch
  ansible.builtin.include_tasks: config-linux-logstash-elastic.yml
  when: "'elastic_siem_role' in group_names"
- name: Configure Logstash
  ansible.builtin.include_tasks: config-linux-logstash.yml
  when: ('logstash_role' in group_names or 'logstash_oss_role' in group_names) and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
