- name: Copy WinLogBeat configuration.
  ansible.windows.win_template:
    src: winlogbeat-logstash.yml.j2
    dest: "{{ winlogbeat_install_location }}/{{ winlogbeat_download_file | replace('oss-', '') }}/winlogbeat.yml"
  notify: Restart Windows Winlogbeat
  when: winlogbeat_logstash == '1'
