---

- name: Set Kibana Password
  ansible.builtin.uri:
    url: https://127.0.0.1:9200/_security/user/kibana_system/_password
    ca_path: '/opt/elasticsearch/config/certs/ca/ca.crt'
    return_content: true
    user: "elastic"
    password: "{{ lookup('community.hashi_vault.vault_kv2_get', 'elastic', engine_mount_point='secrets')['secret']['elasticsearch'] }}"
    method: POST
    body_format: "json"
    body:
      password: "{{ lookup('community.hashi_vault.vault_kv2_get', 'elastic', engine_mount_point='secrets')['secret']['kibana'] }}"

- name: Kibana NonOSS Docker
  become: true
  community.docker.docker_container:
    name: kibana
    image: docker.elastic.co/kibana/kibana:{{ elastic_version }}
    detach: true
    pull: true
    restart_policy: unless-stopped
    networks:
      - name: elk
    env:
      node.name: kibana
      ELASTICSEARCH_HOSTS: "https://elasticsearch:9200"
      ELASTICSEARCH_USERNAME: "kibana_system"
      ELASTICSEARCH_PASSWORD: "{{ lookup('community.hashi_vault.vault_kv2_get', 'elastic', engine_mount_point='secrets')['secret']['kibana'] }}"
      ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES: "config/certs/ca/ca.crt"
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: "{{ lookup('community.hashi_vault.vault_kv2_get', 'elastic', engine_mount_point='secrets')['secret']['XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY'] }}"
    ports:
      - 5601:5601
    volumes:
      - elasticsearch-certs:/usr/share/kibana/config/certs
  when: elastic_non_oss == '1'

- name: Kibana NonOSS Docker
  become: true
  community.docker.docker_container:
    name: kibana
    image: docker.elastic.co/kibana/kibana-oss:{{ elastic_version }}
    detach: true
    pull: true
    restart_policy: unless-stopped
    networks:
      -name: elk
    env:
      node.name: kibana
      ELASTICSEARCH_HOSTS: "https://elasticsearch:9200"
      ELASTICSEARCH_USERNAME: "kibana_system"
      ELASTICSEARCH_PASSWORD: "{{ lookup('community.hashi_vault.vault_kv2_get', 'elastic', engine_mount_point='secrets')['secret']['kibana'] }}"
    volumes:
      - elasticsearch-certs:/usr/share/elastic-certs
    ports:
      - 5601:5601
  when: elastic_oss == '1'
