---

- name: Install Docker
  ansible.builtin.include_tasks: install-linux-docker.yml
  when: "'docker_role' in group_names and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')"
