---

- name: Enable Windows Scriptblock Logging
  failed_when: false
  ansible.windows.win_regedit:
    key: "HKLM:\\Software\\Policies\\Microsoft\\Windows\\PowerShell\\ScriptBlockLogging"
    value: EnableScriptBlockLogging
    datatype: dword
    data: 1
  register: scriptblocklogging1

- name: Enable Windows Scriptblock Logging
  failed_when: false
  ansible.windows.win_regedit:
    key: "HKLM:\\Software\\Policies\\Microsoft\\Windows\\PowerShell\\ScriptBlockLogging"
    value: EnableScriptBlockInvocationLogging
    datatype: dword
    data: 1
  register: scriptblocklogging2

- name: Restart machine
  ansible.windows.win_reboot:
  when: scriptblocklogging1.changed and scriptblocklogging2.changed
