---

- name: Set DNS (Windows)
  ansible.windows.win_dns_client:
    adapter_names: '*'
    dns_servers:
      - "{{ dns_server }}"
  when: ansible_os_family == "Windows" and dns_server is defined

- name: Set Hostname
  ansible.windows.win_hostname:
    name: "{{ hostname }}"
  when: hostname is defined
  register: res

- name: Reboot
  ansible.windows.win_reboot:
  when: res.reboot_required
