---

- name: Install Logstash-OSS
  become: true
  ansible.builtin.apt:
    name: logstash-oss
    update_cache: true
    state: present
  when: elastic_oss == '1'

- name: Install Logstash
  become: true
  ansible.builtin.apt:
    name: logstash
    update_cache: true
    state: present
  when: elastic_non_oss == '1'
