---

- name: Install Logstash
  ansible.builtin.include_tasks: install-linux-logstash.yml
  when: install_logstash == '1' and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
- name: Configure Logstash User and ILM for Elasticsearch
  ansible.builtin.include_tasks: config-linux-logstash-elastic.yml
  when: install_elastic == '1'
- name: Configure Logstash
  ansible.builtin.include_tasks: config-linux-logstash.yml
  when: install_logstash == '1' and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
