---

- name: Install iptables
  become: true
  ansible.builtin.apt:
    name: iptables
    state: present

- name: Masquerade eth1-ens18
  become: true
  ansible.builtin.iptables:
    chain: POSTROUTING
    table: nat
    in_interface: eth1
    out_interface: ens18
    jump: MASQUERADE

- name: HTTPS Forwarding to Polarproxy
  become: true
  ansible.builtin.iptables:
    chain: PREROUTING
    table: nat
    in_interface: eth1
    protocol: tcp
    to_ports: 443
    jump: REDIRECT
    destination_port: 443
    match:
      - tcp

- name: Accept eth1
  become: true
  ansible.builtin.iptables:
    table: INPUT
    in_interface: eth1
    jump: ACCEPT

- name: Accept ens18
  become: true
  ansible.builtin.iptables:
    table: INPUT
    in_interface: ens18
    ctstate:
      - RELATED
      - ESTABLISHED
    jump: ACCEPT

- name: Accept Output
  become: true
  ansible.builtin.iptables:
    table: OUTPUT
    jump: ACCEPT
