---

- name: Install iptables
  become: true
  ansible.builtin.apt:
    name:
      - iptables
      - iptables-persistent
    state: present

- name: Masquerade ens18
  become: true
  ansible.builtin.iptables:
    chain: POSTROUTING
    table: nat
    out_interface: ens18
    jump: MASQUERADE
  notify: Save iptables

- name: HTTPS Forwarding to Polarproxy
  become: true
  ansible.builtin.iptables:
    chain: PREROUTING
    table: nat
    in_interface: eth1
    protocol: tcp
    to_ports: 443
    jump: REDIRECT
    destination_port: 443
    match:
      - tcp
  notify: Save iptables

- name: Accept eth1
  become: true
  ansible.builtin.iptables:
    chain: INPUT
    in_interface: eth1
    jump: ACCEPT
  notify: Save iptables

- name: Accept ens18
  become: true
  ansible.builtin.iptables:
    chain: INPUT
    in_interface: ens18
    ctstate:
      - RELATED
      - ESTABLISHED
    jump: ACCEPT
  notify: Save iptables

- name: Accept Output
  become: true
  ansible.builtin.iptables:
    chain: OUTPUT
    jump: ACCEPT
  notify: Save iptables
