---
- name: Install dhcpd
  become: true
  ansible.builtin.apt:
    name: isc-dhcp-server
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Configure dhcpd
  become: true
  ansible.builtin.copy:
    src: dhcpd.conf
    dst: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: 0640
  notify: Restart DHCPD

- name: DHCPD Service running
  become: true
  ansible.builtin.systemd:
    name: isc-dhcp-server
    state: started
    enabled: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
