---

- name: Deploy InetSim repo
  become: true
  ansible.builtin.copy:
    src: inetsim.list
    dest: /etc/apt/sources.list.d/inetsim.list

- name: Add InetSim Key
  become: true
  ansible.builtin.apt_key:
    url: https://www.inetsim.org/inetsim-archive-signing-key.asc
    state: present

- name: Install InetSim
  become: true
  ansible.builtin.apt:
    name: inetsim
    update_cache: yes
    state: present
